### ISSUE TITLE
metric name auto-completion does not work

### ISSUE THREAD

**Issue by xzchaoo** [traas-stack/holoinsight#118]
## Describe this problem
I have created a log monitoring config.
![image](https://user-images.githubusercontent.com/8319940/218038486-4a551956-5438-460e-8c25-8ea893531471.png)

When I config a dashboard, the metric name auto-completion does not work.
![image](https://user-images.githubusercontent.com/8319940/218037316-13a276a0-3cd0-476a-91b6-c16f0f0b3884.png)

## To Reproduce
See Description

## Expected behavior
metric name auto-completion works

**Comment by jiwliu** [comment]
![image](https://user-images.githubusercontent.com/20149434/231039599-ef10e494-d2e7-49bc-aac4-2f8e427b75cc.png)
For dashboard monitored by the log type, you need to select log monitoring to select the data source

![image](https://user-images.githubusercontent.com/20149434/231040229-c607343d-aa91-4084-8629-c2d24aff8575.png)
