### ISSUE TITLE
Config timezone column 

### ISSUE THREAD

**Issue by zzhb101** [traas-stack/holoinsight#142]
## Describe this problem
The agent will collect the log as "2023-02-20 11:29:21 Hello World" while the log has the formatted timestamp ahead of line, but miss matching log such as "Y|2023-02-20 11:31:21|6" which will be dropped.
And the config for timezone column does not work correctly.
 
## To Reproduce
See above
## Additional Information
None

**Comment by xzchaoo** [comment]
Is this issue a feature or bug?
