### ISSUE TITLE
Http clients cause hot spots

### ISSUE THREAD

**Issue by masaimu** [traas-stack/holoinsight#180]
### Describe this problem

Http client `io.holoinsight.server.home.alert.common.http.HttpProxy` may cause all requests to go to the same server.

### Steps to reproduce

Add ai alert rule, then in each computation cycle, the request traffic to the algorithm visits the same server.

**Comment by xzchaoo** [comment]
"Http client io.holoinsight.server.home.alert.common.http.HttpProxy may cause all requests to go to the same server."
Can you explain why HttpProxy causes all requests to be sent to the same server?
