### ISSUE TITLE
Need clean&simple quickstart base on shell without docker.

### ISSUE THREAD

**Issue by ferdiknight** [traas-stack/holoinsight#186]
### Describe This Problem

Is possible to prepare a non-docker quickstart. Or prepare a tips with docker versions(and other tools like docker-compose). The quick-start is not work for some old version or unclear and complex docker network. It`s hard to start (mostly is blame on docker).

### Proposal

Maybe we can start the mysql mongodb and anyothers with a simple shell on standard linux whatever the distribution is. And so on  the new starters can quickly take a view of the whole software.
Thanks for times.

**Comment by xzchaoo** [comment]
Hi @ferdiknight. Thank you for your feedback.  
Could you provide your docker & docker-compose version info and your computer configuration info?
The 'quick-start' does not use any advanced features of docker & docker-compose. So it is expected to run in most docker versions.

**Comment by xzchaoo** [comment]
The 'Quick Start' demo requires docker-compose V2.
I test docker-compose V1 and docker-compose V2 locally.
docker-compose V1 doesn't work for 'Quick Start' demo.

**Comment by xzchaoo** [comment]
I fix the doc firstly. See https://github.com/traas-stack/holoinsight/pull/187
And I will use another PR to supports docker-compose V1.

**Comment by xzchaoo** [comment]
Hi @ferdiknight .
I test the 'quick start' demo with docker-compose v1.29.2 and docker compose v2.
This two versions work well. I have update the docs with tips about the docker compose version.
See https://github.com/traas-stack/holoinsight/pull/188.

The demo bootstrap is somewhat complicated. It need 3 external db, and need to initialize them(schema or initial data) before running the server. And then install agent into the server container.
I thinks the demo bootstrap based on docker is the best choice.
