### ISSUE TITLE
No data can be found for indicator names containing uppercase letters

### ISSUE THREAD

**Issue by xzchaoo** [traas-stack/holoinsight#260]
## Describe this problem
What this problem is and what happened.

## To Reproduce
Create two log monitoring items with the same configuration content but different metric names.
One contains all lowercase letters, and another one contains some uppercase letters.
Wait a few minutes.
The first one can find the data, but the second one can't find the data.

**Comment by jiwliu** [comment]
After upgrading the ceresdb image to v1.0.0, this problem has been resolved
