### ISSUE TITLE
The up.sh script failed to execute

### ISSUE THREAD

**Issue by masaimu** [traas-stack/holoinsight#312]
## Describe this problem
`./test/scenes/scene-default/../common/up.sh: line 13: /scripts/docker/build.sh: No such file or directory`
Because `$project` is empty.

## To Reproduce
![image](https://user-images.githubusercontent.com/12896475/229673809-b4156856-0238-4961-a69a-ca8960fa0f16.png)

**Comment by xzchaoo** [comment]
Do you use latest holoinsight code ?
