### ISSUE TITLE
安装完后怎么添加主机？

### ISSUE THREAD

**Issue by James601232** [traas-stack/holoinsight#842]
## Describe this problem
按照这个步骤安装完后，界面正常打开，但是无法添加主机，怎么添加主机等？
https://traas-stack.github.io/holoinsight-docs/cn/introduction/quick-start.html
## To Reproduce
How to reproduce this problem.

## Expected behavior
What is your expected behavior.

## Additional Information
If possible, please attach other context you think may relate to this problem. Like runtime environment, modified config, error log etc.

**Comment by jsy1001de** [comment]
You need to install holoinsight-agent，/scripts/docker/bin/start.sh

**Comment by James601232** [comment]
dose holoinsight team has community channel?  eg webchat or others

**Comment by James601232** [comment]
@jsy1001de  dingtalk-qrcode.jpg is expire. can you share new qrcode?

**Comment by jsy1001de** [comment]
> @jsy1001de dingtalk-qrcode.jpg is expire. can you share new qrcode?

have updated

**Comment by James601232** [comment]
@jsy1001de  join dingtalk failed. screenshot is :
![WechatIMG296](https://github.com/traas-stack/holoinsight/assets/19258506/05787fb7-04bd-41ee-9de6-aecf8c09ac6e)

**Comment by James601232** [comment]
@jsy1001de Please check whether the DingTalk QRcode fine?

**Comment by James601232** [comment]
@suziewong @kongluoxing 
Dear guys. help checked dingtalk qrcode why couldn't  join successful.
![Uploading image.png…]()

**Comment by jsy1001de** [comment]
> @suziewong @kongluoxing Dear guys. help checked dingtalk qrcode why couldn't join successful.

It has been resolved. Please try scanning the code again
